name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops:${{ github.run_number }}
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: update k8s manifest
        run: |
          sed -i 's|${{ secrets.DOCKER_USERNAME }}/devops:.*|${{ secrets.DOCKER_USERNAME }}/devops:${{ github.run_number }}|' k8s-manifests/deployment.yaml
    
      - name: git push
        run: |  
          git config --global user.email "bobba.brahmareddy@gmail.com"
          git config --global user.name "Brahma Reddy Bobba"     
          git add k8s-manifests/deployment.yaml
          git commit -m "update deployment.yaml"
          git push
      
